name: "selective"

on:
  push:
    branches:
      - test

jobs:
  check:
    name: Check files

    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified files
        id: check_files
        run: |
          echo "========== check paths of modified files =========="
          git diff --dirstat=files,0 HEAD~1 | sed 's/^[ 0-9.]\+% //g' >> out.txt
          cat out.txt
          ls -al

          jq -Rs '[ split("\n")[] | split("\r")[] | select(length > 0) | split(",") |{path: .[0]} ]' out.txt >> out.json
          cat out.json

      - name: Set matrix data
        id: set-matrix
        run: |
          ls
          echo "matrix=$(jq -c . < ./out.json)" >> $GITHUB_OUTPUT

  print:
    runs-on: ubuntu-latest
    needs: check
    strategy:
      matrix: 
        package: ${{ fromJson(needs.check.outputs.matrix) }}
    steps:
      - run: echo running for ${{matrix.package.path}}




