name: "selective"

on:
  push:
    branches:
      - test

jobs:

  loop:
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    runs-on: ubuntu-latest
    steps:
    # output what you want, the output of package B will be available in needs for furture jobs
    - run: echo "MyKey=MyOutput" > $GITHUB_OUTPUT
      id: mystep
      if: matrix.package == 'B' 
    outputs:
      B: ${{ steps.mystep.outputs.mykey || '' }}