name: "selective"

on:
  push:
    branches:
      - test

jobs:

  loop:
    strategy:
      matrix:
        package: ${{fromJson(needs.check_files.GITHUB_OUTPUT.run_job)}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified files
        id: check_files
        run: |
          git diff --name-only HEAD^ HEAD >> files.txt
          while IFS= read -r file
          do
            echo "{run_job}={false}" >> $GITHUB_OUTPUT
          done < files.txt


      - name: check modified files
        run: ${{ tojson(needs) }}
        shell: cat {0]